
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - manuth.eslint-language-service
    - esbenp.prettier-vscode
